language: go
sudo: false
go:
  - 1.11.x
  - 1.12.x
  - tip

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
